### ISSUE TITLE
Profile and optimize the ECS

### ISSUE THREAD

**Issue by RiscadoA** [GameDevTecnico/cubos#1025]
# Checklist
- [ ] Write some profiling tests for the ECS and identify slow points
- [ ] Skip query archetype nodes which run after related nodes
- [ ] TODO fill this with problems discovered while profiling

# Problem
Our current ECS is efficient algorithmically, but in practice not much care was taken to write fast code.
We should profile it and identify the bottlenecks we have, and try to improve them as much as possible.
