### ISSUE TITLE
Have a minimal in-house UI which we can use for games

### ISSUE THREAD

**Issue by RiscadoA** [GameDevTecnico/cubos#1112]
# Checklist
- [ ] Add UICanvas, UIElement and boxes
- [ ] Add Anchors
- [ ] Add UI Pressed and Hovered components
- [ ] Add UI images
- [ ] Add UI text
