### ISSUE TITLE
Collisions

### ISSUE THREAD

**Issue by fallenatlas** [GameDevTecnico/cubos#1346]
# Collision Enhancements

### Shapes:
- [ ] Add collision computation for capsule
- [ ] Add collision computation for sphere
- [ ] Add manifold computation for capsule (add inertia tensor calculation)
- [ ] Add manifold computation for sphere (add inertia tensor calculation)

### Feature:
- [ ] Collision layers and collision masks

### Optimization:
- [ ] Optimize broad phase collisions (maybe use BVH)
- [ ] Measure collisions performance

# Problem
Box shape is currently the only simple shape with collision computation. We should start looking into implementing alternative shapes.

**Comment by fallenatlas** [comment]
There is already a collisions tracking issue, moved there
