### ISSUE TITLE
Enhance CMake build configuration

### ISSUE THREAD

**Issue by RiscadoA** [GameDevTecnico/cubos#332]
The current config is full of duplicated code and is lacking a lot of helpful features:
- [ ] code formatting: clang-format (it could be integrated here)
- [X] static analysis: clang-tidy
- [ ] dynamic analysis: sanitizers, valgrind, etc

Useful resources:
- https://cliutils.gitlab.io/modern-cmake/
- https://github.com/friendlyanon/cmake-init/

**Comment by RiscadoA** [comment]
Pretty much done, will split the small tasks into other issues
