### ISSUE TITLE
Collisions

### ISSUE THREAD

**Issue by luishfonseca** [GameDevTecnico/cubos#655]
# Checklist

- [ ] Cleanup Broadphase
  - [ ] Remove useless shapes
  - [ ] Replace Broadphase resource with ECS solution
  - [ ] Split Collider and ColliderShape
- [ ] Narrowphase
  - [ ] Add BoxBox intersection test to core::geom
  - [ ] Add BoxCapsule intersection test to core::geom
  - [ ] Add CapsuleCapsule intersection test to core::geom
  - [ ] Detect collisions
  - [ ] Generate contacts
- [ ] Better Broadphase
  - [ ] Add VoxelShape
  - [ ] Implement Local BVH for VoxelShapes
  - [ ] Optimize World with BVH

# Problem
I was young and naive when I designed what we have so far, it's time to rewrite.

# Design
Fill this later
