### ISSUE TITLE
Add alternative sources for axis

### ISSUE THREAD

**Issue by RiscadoA** [GameDevTecnico/cubos#843]
# Checklist
- [ ] Refactor existing axis sources code to something more abstract
- [ ] Allow using mouse movement as an axis source
- [ ] Allow using gamepad buttons as positive/negative axis sources

# Problem
Currently we only support setting keys and joysticks as axis sources.

# Design
WIP - we should prevent code duplication and find some abstractions we can use instead of just copying the logic 4x times.
